repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
        exclude: &exclude_txtfiles >-
          (?x)^(
              example/.*.eig|
              example/.*.xml|
              example/.*EIGENVAL|
              example/.*KPOINTS|
              example/.*OUTCAR|
              example/.*POSCAR|
              example/.*.dat|
              example/.*.freq|
              example/.*.in|
              example/.*.win
          )$
      - id: fix-encoding-pragma
        args: ["--remove"]
        exclude: *exclude_txtfiles
      - id: mixed-line-ending
        exclude: *exclude_txtfiles
      - id: trailing-whitespace
        exclude: *exclude_txtfiles
      - id: check-json
      - id: check-yaml
      - id: check-toml

  # - repo: https://github.com/mgedmin/check-manifest
  #   rev: "0.48"
  #   hooks:
  #     - id: check-manifest

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.0
    hooks:
      - id: pyupgrade
        args: ["--py37-plus"]

  - repo: https://github.com/ikamensh/flynt/
    rev: "1.0.1"
    hooks:
      - id: flynt
        args: ["--line-length=120", "--fail-on-change"]

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        additional_dependencies: ["toml"]

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args: ["--ignore=D104,D202,D203,D213"]

  - repo: https://github.com/PyCQA/pylint
    rev: v3.3.1
    hooks:
      - id: pylint
        language: system
